# Generated by Django 5.1.2 on 2024-10-25 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileUpload',
            new_name='UploadedFile',
        ),
    ]
